WARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000238429696D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4fe4f378d0c2f89da9b3a7811b331c54
WARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002384213CBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4fe4f378d0c2f89da9b3a7811b331c54
WARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023841B83438>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4fe4f378d0c2f89da9b3a7811b331c54